# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: ../lighter/images/train/
val: ../lighter/images/val/
test: ../lighter/images/test/

# number of classes
nc: 1

# class names
names: ['lighter']